# set prefix to ctrl+s
unbind C-b
set-option -g prefix C-s
bind C-s send-prefix

# reload tmux conf with prefix+r
unbind r
bind r source-file ~/.tmux.conf

# count panes from 1
set -g base-index 1
setw -g pane-base-index 1

